### PR TITLE
[FIX]: Team Repo Removed from list on backspace

### PR DESCRIPTION
**Pull request by VipinDevelops**
## Linked Issue(s) 
#510 

## Acceptance Criteria fulfillment

- [x] Does Not Impact Existing behavior of the Input
- [x] Existing Repos don't get deleted from the team repos list.

## Proposed changes (including videos or screenshots)

[Screencast from 2024-08-08 22-41-30.webm](https://github.com/user-attachments/assets/890338be-bc68-4db6-a769-ca93d5b7181d)

Screenshot from 2024-08-08 23-09-40

### CODE REVIEW

**Comment by VipinDevelops** [comment]
Hey @samad-yar-khan ,

I fixed the issue. I started by looking into the `onChange` handler and the search query. I checked `[useTeamConfig](https://github.com/middlewarehq/middleware/blob/798c52c52cba509fbe2614f6542d72f2df333b4b/web-server/src/components/Teams/useTeamsConfig.tsx)` thoroughly, and everything was perfectly fine there. I tried running multiple debugging sessions but found nothing. 

It hit me that maybe there was something wrong with the `Autocomplete` component internally—perhaps a default behavior or something—because it was just deleting the last value from the repos and that to when *Back Space* is pressed.

I ran a few experiments in my personal project to confirm this theory, and indeed I was correct. I found that the behavior of the backspace key in the `Autocomplete` component (when using multiple values) is such that pressing backspace will delete the rightmost selected item.

The solution was to override or compose key-down events in `Autocomplete`. I just prevented it from propagating, and it worked.

**Comment by jayantbh** [comment]
@VipinDevelops this fix feels hacky.
I expect the issue lies in some other event handler logic going wrong.

Could you check if there's a better way to fix this?

**Comment by VipinDevelops** [comment]
Hey @jayantbh  I agree this looks a bit hacky but I have Tried and Tested everything in the logic and there is nothing wrong, I was also thinking the same that there might be some state change issue with a key press or something but no logic is correct it just a default behavior (It took me some time to figure it out).

Here is a [PR Link](https://github.com/mui/material-ui/issues/21129) that talks about the same issue in MUI itself and although it's a bit hacky I think the only why because one of the maintainers suggested it.

**Comment by jayantbh** [comment]
Well... I see. In that case, the comments later in the thread suggest handling for other keys as well. Maybe you could test and handle for those as well?

**Comment by VipinDevelops** [comment]
Sure @jayantbh  I will test out and update the *Delete*  *ArrowLeft* Keys as well.
Sounds good?

**Comment by jayantbh** [comment]
@VipinDevelops sounds good

**Comment by VipinDevelops** [comment]
[Screencast from 2024-08-10 03-49-32.webm](https://github.com/user-attachments/assets/43e02e6a-557c-412c-b4ab-01d0d13293f3)

Hey @jayantbh I tested it out we have no problem with Delete or Left Arrow in our case

**Review by jayantbh — APPROVED** [review]

**Comment by jayantbh** [comment]
Hey @VipinDevelops, I've merged it. Congrats on closing this one!

**Comment by VipinDevelops** [comment]
Thanks Jayant ☺️

**Pull request merged**
