### PR TITLE
Fix 366

### LINKED ISSUE #366: Remove User not added tooltip
### Description:
On hovering over author in PR details, we get this tool tip saying User not added to MHQ. 
Screenshot 2024-05-18 at 8 00 37 AM

### Steps to reproduce:

1. Go to http://localhost:3333/dora-metrics
2. Click on See Details on Lead Time
Screenshot 2024-05-18 at 8 03 41 AM
3. In the list that opens up, hover on the author

### Expected behavior:

Since we're not adding any user level data, we should remove this tool tip.

### PR DESCRIPTION
**Pull request by gajrajgchouhan**
## Linked Issue(s) 

Closes #366 

## Acceptance Criteria fulfillment

- [ ] Task 1
- [ ] Task 2
- [ ] Task 3

### CODE REVIEW

**Comment by gajrajgchouhan** [comment]
There is a `PullRequestsTableMini` as well, do I need to change that as well?

**Review by kumarajay0412 — APPROVED** [review]

**Comment by samad-yar-khan** [comment]
@e-for-eshaan  Can you please look into these front-end changes ?

**Comment by e-for-eshaan** [comment]
Hey @gajrajgchouhan, thanks for this PR.
The `DeploymentInsightsOverlay` (the one that opens when you click on the Deployment Frequency card) utilises `PullRequestsTableMini`. You should remove the redundant copy from there as well.

**Comment by gajrajgchouhan** [comment]
Hi @e-for-eshaan , I have done this.

**Review by e-for-eshaan — APPROVED** [review]
LGTM

**Pull request merged**
