### PR TITLE
feat: add team view button

### PR DESCRIPTION
**Pull request by xyfer17**
## Linked Issue(s)

#540 

## Acceptance Criteria fulfillment

- [x] Add a team view button that redirects to the dora-page, showing dora-data of the team

## Proposed changes (including videos or screenshots)

https://github.com/user-attachments/assets/1ba38d7f-c393-41ff-8588-7b121b682b61

## Further comments

As per the issue #540, add the tiny-pill button named dora which redirect dora page, showing dora-data of the team

### CODE REVIEW

**Comment by xyfer17** [comment]
Hey @e-for-eshaan

Can you Please take a look ?
Thanks :)

**Comment by jayantbh** [comment]
Functionally it's there, but visually it leaves some room to be improved.
Suggestions on how we can improve this visually?
@xyfer17 @e-for-eshaan

**Comment by xyfer17** [comment]
@jayantbh could you please suggest any ui change make it's visual look better ?

**Comment by jayantbh** [comment]
We'll share our shot at the visual changes soon.
Meanwhile, could you ensure the linter has run correctly? The CI caught some linting issues.

**Comment by xyfer17** [comment]
> We'll share our shot at the visual changes soon. Meanwhile, could you ensure the linter has run correctly? The CI caught some linting issues.

have fixed the linting issues

**Comment by jayantbh** [comment]
Hey @xyfer17, apologies for the silence on this.
SVG:
</img>

Please use this logo/icon instead of the button in its current form.

Basically, make it so that it looks and behaves like the other icon buttons:
image

And clicking on it should do the same thing that it does today.

**Comment by xyfer17** [comment]
> Hey @xyfer17, apologies for the silence on this. SVG: 
> 
> Please use this logo/icon instead of the button in its current form.
> 
> Basically, make it so that it looks and behaves like the other icon buttons: image
> 
> And clicking on it should do the same thing that it does today.

sure I'll do it and let you know after the change.

**Review by jayantbh — APPROVED** [review]

**Pull request merged**
