### PR TITLE
Fixed CLI log switching between different Log Sources

### LINKED ISSUE #238: CLI not switching to API logs when needed
### Description:

Whenever I run the product in dev mode, I am not able to switch logs between web server and api server.

### Steps to reproduce:

1.  `./dev.sh`
2.  switch between server logs. and switch to api-server logs. `[w]`

### Expected behaviour:

- It should switch logs to API server.

### Actual behavior:

- Cant switch between logs.
image

### Server Setup Information:

- Operating System: Mac OS 14
- Deployment Method:

### PR DESCRIPTION
**Pull request by Kamlesh72**
## Linked Issue(s) 

Closes #238 

## Proposed changes (including videos or screenshots)

User can now easily switch logs for different sources such as "API", "Web", "Redis" etc.

### CODE REVIEW

**Comment by amoghjalan** [comment]
Hey @Kamlesh72 
I tested your changes and the problem doesn't seem to have been solved. 
Steps to reproduce:
1. Click `q` for web-server logs
2. Try clicking for any other keys it doesn't work.
Though it does work for when you go to 't` and then try going to any other logs except sync_server logs

**Comment by Kamlesh72** [comment]
@amoghjalan Can you have a look at https://github.com/middlewarehq/middleware/issues/238#issuecomment-2220389938 if this is the preferred change?
I again tried and was able to go to all sources from "web-server".
I used `./dev.sh` to run the code.

**Comment by Kamlesh72** [comment]
@jayantbh @amoghjalan Any updates on this?

**Comment by jayantbh** [comment]
Getting this checked soon. Apologies for the delay.

**Comment by jayantbh** [comment]
@Kamlesh72 in your original screenshot, you've changed `setLogsStream`
image

But in this PR, you've updated `setLogSource`, which should also have thrown a typescript error for you.
image

Perhaps that's why it didn't work for Amogh.

**Comment by Kamlesh72** [comment]
@jayantbh Thanks a lot. I Mistakenly have 2 repos locally, which caused some confusion for me. I apologize for the same. I made the commit to fix it.

**Comment by e-for-eshaan** [comment]
LGTM!
cc: @jayantbh 
tested for log switching and preservation.

**Review by e-for-eshaan — APPROVED** [review]

**Comment by jayantbh** [comment]
Congrats on the merge, @Kamlesh72!
Looking forward to more such contributions!

There are many issues under [Good First Issues](https://github.com/middlewarehq/middleware/issues?q=is:issue+is:open+label:%22good+first+issue%22) that you could check.

**Pull request merged**
